---
apiVersion: v1
kind: Secret
metadata:
  name: ${{ values.name }}-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://${{ values.host }}/${{ values.owner }}/${{ values.destination }}